<a href="https://colab.research.google.com/github/maicongiehl/unijui-programacao-para-ciencia-de-dados/blob/dev/aulas/aula-12/Atividade_Aula_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [122]:
# 1. Buscar o dataset e 2. Inserir no pandas
import pandas as pd

nomes = [
    'Ácido Fixo', # "fixed acidity",
    'Ácido Volátil', # "volatile acidity",
    'Ácido Cítrico', # "citric acid",
    'Açúcar Residual', # "residual sugar",
    'Clorídeos', # "chlorides",
    'Dióxido de Enxofre Livre', # "free sulfur dioxide",
    'Dióxido de Enxofre Total', # "total sulfur dioxide",
    'Densidade', # "density",
    'pH', # "pH",
    'Sulfato', # "sulphates",
    'Álcool', # "alcohol",
    'Qualidade', # "quality"
]

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv', names = nomes, sep=';', skiprows=1)
df.head()

,Ácido Fixo,Ácido Volátil,Ácido Cítrico,Açúcar Residual,Clorídeos,Dióxido de Enxofre Livre,Dióxido de Enxofre Total,Densidade,pH,Sulfato,Álcool,Qualidade
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [123]:
# 3. Inserir uma coluna adicional com a classsificação ( de acorco com a tabela abaixo):

# Baixa: nota menor ou igual a 4.
# Média: nota 5 ou 6.
# Alta: nota maior ou igual a 7.
# Obs: Essa classificação é para efeitos academicos

import numpy as np

condicoes = [df["Qualidade"] >= 7, df["Qualidade"] >= 5, df["Qualidade"] < 5]
resultados = ["Alta", "Média", "Baixa"]

df["Classificação"] = np.select(condicoes, resultados, default="Desconhecido")

# df.loc[df["Qualidade"] == 5].head()
df.head()

,Ácido Fixo,Ácido Volátil,Ácido Cítrico,Açúcar Residual,Clorídeos,Dióxido de Enxofre Livre,Dióxido de Enxofre Total,Densidade,pH,Sulfato,Álcool,Qualidade,Classificação
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Média
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,Média
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,Média
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,Média
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Média

In [124]:
# 5. Separar os dados de alvo (classificação)
from sklearn.preprocessing import StandardScaler

X = df[df.columns.difference(['Classificação', 'Qualidade'])].values
print(f'X: {X}')

scaler = StandardScaler()
X = scaler.fit_transform(X)

y = df['Classificação'].values
print(f'Y: {y}')

X: [[ 1.9      0.076    0.9978  ...  7.4      0.7      9.4    ]
 [ 2.6      0.098    0.9968  ...  7.8      0.88     9.8    ]
 [ 2.3      0.092    0.997   ...  7.8      0.76     9.8    ]
 ...
 [ 2.3      0.076    0.99574 ...  6.3      0.51    11.     ]
 [ 2.       0.075    0.99547 ...  5.9      0.645   10.2    ]
 [ 3.6      0.067    0.99549 ...  6.       0.31    11.     ]]
Y: ['Média' 'Média' 'Média' ... 'Média' 'Média' 'Média']

In [125]:
# 6. Treinar o modelo KNN (escolha aleatoriamente o numero de vizinhos)
from sklearn.neighbors import KNeighborsClassifier

vinho_classificador = KNeighborsClassifier(n_neighbors=5)

vinho_classificador.fit(X, y)

KNeighborsClassifier()

In [126]:
# 7. Confira a acurácia do algoritmo
from sklearn.model_selection import cross_val_score

scores_dt = cross_val_score(vinho_classificador, X, y, scoring='accuracy', cv=5)

print(scores_dt.mean())

0.7948687304075236

In [127]:
# 8. Teste com outros valores de vizinhos buscando melhorar a acurácia.

maior_acuracia_i = 0
maior_acuracia_mean = 0
for i in range(1, 100):
  vinho_classificador = KNeighborsClassifier(n_neighbors= i)
  vinho_classificador.fit(X, y)
  scores_dt = cross_val_score(vinho_classificador, X, y, scoring='accuracy', cv=5)

  if scores_dt.mean() > maior_acuracia_mean:
    maior_acuracia_i = i
    maior_acuracia_mean = scores_dt.mean()

  print(f'VIzinhos: {i} Acurácia: {scores_dt.mean()}')


print(f"Maior acurácia: {maior_acuracia_mean}, usando {maior_acuracia_i} vizinhos")

VIzinhos: 1 Acurácia: 0.7561030564263324
VIzinhos: 2 Acurácia: 0.7023275862068965
VIzinhos: 3 Acurácia: 0.7986167711598746
VIzinhos: 4 Acurácia: 0.7711246081504701
VIzinhos: 5 Acurácia: 0.7948687304075236
VIzinhos: 6 Acurácia: 0.7948746081504703
VIzinhos: 7 Acurácia: 0.8086363636363636
VIzinhos: 8 Acurácia: 0.8023765673981191
VIzinhos: 9 Acurácia: 0.8130133228840126
VIzinhos: 10 Acurácia: 0.8148844043887147
VIzinhos: 11 Acurácia: 0.8130094043887148
VIzinhos: 12 Acurácia: 0.8117692006269592
VIzinhos: 13 Acurácia: 0.8167672413793102
VIzinhos: 14 Acurácia: 0.8167711598746081
VIzinhos: 15 Acurácia: 0.8111422413793103
VIzinhos: 16 Acurácia: 0.8092711598746082
VIzinhos: 17 Acurácia: 0.8105172413793102
VIzinhos: 18 Acurácia: 0.8080211598746081
VIzinhos: 19 Acurácia: 0.8130152821316614
VIzinhos: 20 Acurácia: 0.8117672413793103
VIzinhos: 21 Acurácia: 0.8142633228840126
VIzinhos: 22 Acurácia: 0.8136422413793103
VIzinhos: 23 Acurácia: 0.8136383228840126
VIzinhos: 24 Acurácia: 0.8123844043887148
VIzinhos: 25 Acurácia: 0.8148902821316615
VIzinhos: 26 Acurácia: 0.8161422413793102
VIzinhos: 27 Acurácia: 0.8186402821316614
VIzinhos: 28 Acurácia: 0.8192672413793103
VIzinhos: 29 Acurácia: 0.8205152821316615
VIzinhos: 30 Acurácia: 0.8198922413793104
VIzinhos: 31 Acurácia: 0.8211442006269593
VIzinhos: 32 Acurácia: 0.8205211598746083
VIzinhos: 33 Acurácia: 0.8217692006269592
VIzinhos: 34 Acurácia: 0.8211481191222572
VIzinhos: 35 Acurácia: 0.821771159874608
VIzinhos: 36 Acurácia: 0.822398119122257
VIzinhos: 37 Acurácia: 0.8223942006269592
VIzinhos: 38 Acurácia: 0.8242711598746082
VIzinhos: 39 Acurácia: 0.8273961598746082
VIzinhos: 40 Acurácia: 0.8255211598746082
VIzinhos: 41 Acurácia: 0.8280211598746081
VIzinhos: 42 Acurácia: 0.8255211598746082
VIzinhos: 43 Acurácia: 0.826146159874608
VIzinhos: 44 Acurácia: 0.8242692006269593
VIzinhos: 45 Acurácia: 0.8248942006269593
VIzinhos: 46 Acurácia: 0.8248942006269593
VIzinhos: 47 Acurácia: 0.8255192006269592
VIzinhos: 48 Acurácia: 0.8248961598746082
VIzinhos: 49 Acurácia: 0.8255211598746082
VIzinhos: 50 Acurácia: 0.8248942006269593
VIzinhos: 51 Acurácia: 0.8255211598746082
VIzinhos: 52 Acurácia: 0.8261442006269594
VIzinhos: 53 Acurácia: 0.8255172413793105
VIzinhos: 54 Acurácia: 0.8261422413793105
VIzinhos: 55 Acurácia: 0.8273922413793103
VIzinhos: 56 Acurácia: 0.8248902821316616
VIzinhos: 57 Acurácia: 0.8261402821316615
VIzinhos: 58 Acurácia: 0.8273922413793103
VIzinhos: 59 Acurácia: 0.8286442006269592
VIzinhos: 60 Acurácia: 0.8292692006269592
VIzinhos: 61 Acurácia: 0.8305211598746081
VIzinhos: 62 Acurácia: 0.8286442006269592
VIzinhos: 63 Acurácia: 0.8323961598746081
VIzinhos: 64 Acurácia: 0.8298922413793104
VIzinhos: 65 Acurácia: 0.8305172413793104
VIzinhos: 66 Acurácia: 0.8298922413793104
VIzinhos: 67 Acurácia: 0.8311422413793104
VIzinhos: 68 Acurácia: 0.8292672413793104
VIzinhos: 69 Acurácia: 0.8305172413793104
VIzinhos: 70 Acurácia: 0.8311422413793104
VIzinhos: 71 Acurácia: 0.8311422413793104
VIzinhos: 72 Acurácia: 0.8317672413793102
VIzinhos: 73 Acurácia: 0.8298902821316615
VIzinhos: 74 Acurácia: 0.8311422413793104
VIzinhos: 75 Acurácia: 0.8317711598746081
VIzinhos: 76 Acurácia: 0.8317711598746081
VIzinhos: 77 Acurácia: 0.8292652821316615
VIzinhos: 78 Acurácia: 0.8305172413793104
VIzinhos: 79 Acurácia: 0.8311442006269593
VIzinhos: 80 Acurácia: 0.8292672413793104
VIzinhos: 81 Acurácia: 0.8298922413793104
VIzinhos: 82 Acurácia: 0.8292672413793104
VIzinhos: 83 Acurácia: 0.8292672413793104
VIzinhos: 84 Acurácia: 0.8286422413793104
VIzinhos: 85 Acurácia: 0.8286422413793103
VIzinhos: 86 Acurácia: 0.8292672413793104
VIzinhos: 87 Acurácia: 0.8292672413793103
VIzinhos: 88 Acurácia: 0.8280172413793103
VIzinhos: 89 Acurácia: 0.8298922413793104
VIzinhos: 90 Acurácia: 0.8280172413793103
VIzinhos: 91 Acurácia: 0.8273922413793103
VIzinhos: 92 Acurácia: 0.8267672413793102
VIzinhos: 93 Acurácia: 0.8273922413793103
VIzinhos: 94 Acurácia: 0.8280172413793103
VIzinhos: 95 Acurácia: 0.8280172413793103
VIzinhos: 96 Acurácia: 0.8273922413793103
VIzinhos: 97 Acurácia: 0.8286422413793103
VIzinhos: 98 Acurácia: 0.8267672413793103
VIzinhos: 99 Acurácia: 0.8273922413793103
Maior acurácia: 0.8323961598746081, usando 63 vizinhos